{
  "openapi": "3.0.1",
  "info": {
    "title": "Supernormal API",
    "description": "Documentation for the Supernormal API",
    "license": {
      "name": "MIT"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://api.supernormal.com/api/v1"
    }
  ],
  "security": [
    {
      "ApiKeyAuth": []
    }
  ],
  "tags": [
    {
      "name": "Agents",
      "description": "Operations about agents"
    },
    {
      "name": "Calendar Events",
      "description": "Operations about calendar"
    },
    {
      "name": "Posts",
      "description": "Operations about posts"
    },
    {
      "name": "Current User",
      "description": "Operations about user"
    }
  ],
  "paths": {
    "/user": {
      "get": {
        "tags": ["Current User"],
        "summary": "Get user",
        "security": [
          {
            "ApiKeyAuth": ["user:read"]
          }
        ]
      }
    },
    "/user/calendar_events": {
      "get": {
        "tags": ["Current User"],
        "summary": "Upcoming calendar events",
        "security": [
          {
            "ApiKeyAuth": ["calendar_events:read"]
          }
        ]
      }
    },
    "/posts": {
      "get": {
        "tags": ["Posts"],
        "summary": "Get posts",
        "description": "Returns the current user's posts",
        "security": [
          {
            "ApiKeyAuth": ["posts:read"]
          }
        ]
      }
    },
    "/posts/{id}": {
      "get": {
        "tags": ["Posts"],
        "summary": "Get a post",
        "description": "Returns a specific post",
        "security": [
          {
            "ApiKeyAuth": ["posts:read"]
          }
        ]
      }
    },
    "/calendar_events/{id}/record": {
      "post": {
        "tags": ["Calendar Events"],
        "summary": "Toggle recording",
        "description": "Toggles whether a calendar event should be recorded",
        "security": [
          {
            "ApiKeyAuth": ["calendar_events:write"]
          }
        ]
      }
    },
    "/agents": {
      "get": {
        "tags": ["Agents"],
        "summary": "Get agents",
        "description": "Returns the current user's agents",
        "security": [
          {
            "ApiKeyAuth": ["agents:read"]
          }
        ]
      },
      "post": {
        "tags": ["Agents"],
        "summary": "Create an agent",
        "description": "Creates an agent",
        "security": [
          {
            "ApiKeyAuth": ["agents:write"]
          }
        ]
      }
    },
    "/agents/{id}": {
      "get": {
        "tags": ["Agents"],
        "summary": "Get an agent",
        "description": "Returns a specific agent",
        "security": [
          {
            "ApiKeyAuth": ["agents:read"]
          }
        ]
      }
    },
    "/agents/{id}/publish": {
      "post": {
        "tags": ["Agents"],
        "summary": "Publish an agent",
        "security": [
          {
            "ApiKeyAuth": ["agents:write"]
          }
        ]
      }
    },
    "/agents/{id}/unpublish": {
      "post": {
        "tags": ["Agents"],
        "summary": "Unpublish an agent",
        "security": [
          {
            "ApiKeyAuth": ["agents:write"]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-TOKEN",
        "x-scopes": {
          "user:read": "Read user information",
          "calendar_events:read": "Read calendar events",
          "calendar_events:write": "Write calendar events"
        }
      }
    }
  }
}
